In [1]:
import pandas as pd 
import numpy as np

In [2]:
df=pd.read_csv('cars.csv')
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [3]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [4]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df.iloc[:,0:4],df.iloc[:,-1])

In [5]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(drop='first',dtype=np.int32,)
x_train_new=ohe.fit_transform(x_train[['fuel','owner']])
x_train_new.shape
x_test_new=ohe.transform(x_test[['fuel','owner']])

In [6]:
print(x_test_new)

<Compressed Sparse Row sparse matrix of dtype 'int32'
	with 2718 stored elements and shape (2032, 7)>
  Coords	Values
  (0, 2)	1
  (0, 6)	1
  (1, 0)	1
  (2, 0)	1
  (2, 6)	1
  (3, 2)	1
  (4, 2)	1
  (4, 4)	1
  (5, 0)	1
  (6, 0)	1
  (6, 4)	1
  (7, 2)	1
  (8, 0)	1
  (9, 0)	1
  (9, 4)	1
  (10, 2)	1
  (11, 0)	1
  (11, 4)	1
  (12, 0)	1
  (13, 2)	1
  (14, 2)	1
  (15, 2)	1
  (16, 0)	1
  (17, 0)	1
  (17, 4)	1
  :	:
  (2013, 2)	1
  (2014, 2)	1
  (2015, 0)	1
  (2015, 6)	1
  (2016, 2)	1
  (2017, 2)	1
  (2017, 4)	1
  (2018, 0)	1
  (2019, 0)	1
  (2020, 0)	1
  (2020, 4)	1
  (2021, 2)	1
  (2022, 1)	1
  (2023, 0)	1
  (2024, 2)	1
  (2024, 4)	1
  (2025, 0)	1
  (2026, 2)	1
  (2026, 6)	1
  (2027, 0)	1
  (2028, 2)	1
  (2029, 0)	1
  (2029, 4)	1
  (2030, 0)	1
  (2031, 0)	1

In [7]:
counts=df['brand'].value_counts()
df['brand'].nunique()
threhold=100
repl=counts[counts<= threhold].index
pd.get_dummies(df['brand'].replace(repl,'uncom'))

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncom
0,False,False,False,False,False,False,True,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,True,False,False,False,False
2,False,False,False,True,False,False,False,False,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,True,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,False,False,False,False,True,False,False,False,False,False,False,False,False
8124,False,False,False,False,True,False,False,False,False,False,False,False,False
8125,False,False,False,False,False,False,True,False,False,False,False,False,False
8126,False,False,False,False,False,False,False,False,False,True,False,False,False
8127,False,False,False,False,False,False,False,False,False,True,False,False,False

In [8]:
df1=pd.read_csv("Amazon Echo 2 Reviews.csv")
df1.head(5)

,Pageurl,Title,Review Text,Review Color,User Verified,Review Date,Review Useful Count,Configuration Text,Rating,Declaration Text
0,https://www.amazon.com/All-New-Amazon-Echo-Dot...,Three Stars,Not great speakers,Black,Verified Purchase,10/3/2017,NaN,Echo Dot,3,NaN
1,https://www.amazon.com/All-New-Amazon-Echo-Dot...,Four Stars,Great little gagit,White,Verified Purchase,9/26/2017,NaN,Echo Dot,4,NaN
2,https://www.amazon.com/All-New-Amazon-Echo-Dot...,Awesome!,Awesome 👏🏽,White,Verified Purchase,9/8/2017,NaN,Echo Dot,5,NaN
3,https://www.amazon.com/All-New-Amazon-Echo-Dot...,Five Stars,Love my Echo,Black,Verified Purchase,10/19/2017,NaN,Echo Dot,5,NaN
4,https://www.amazon.com/All-New-Amazon-Echo-Dot...,Five Stars,Great device,Black,Verified Purchase,9/17/2017,NaN,Echo Dot,5,NaN

In [9]:
df1['Title'].nunique()

3411

In [10]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()


x_train1,x_test1,y_train1,y_test1=train_test_split(df1.iloc[:,2],df1.iloc[:,3])

In [11]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('covid_toy.csv')
df.head(5)

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [13]:
from sklearn.compose import ColumnTransformer

In [14]:
transformer = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']]),['cough']),
    ('tnf3',OneHotEncoder(drop='first'),['gender','city'])
],remainder='passthrough')

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['has_covid']),df['has_covid'],
                                                test_size=0.2)


hell=transformer.fit_transform(X_train)
hell
df

    age  gender  fever   cough       city has_covid
0    60    Male  103.0    Mild    Kolkata        No
1    27    Male  100.0    Mild      Delhi       Yes
2    42    Male  101.0    Mild      Delhi        No
3    31  Female   98.0    Mild    Kolkata        No
4    65  Female  101.0    Mild     Mumbai        No
..  ...     ...    ...     ...        ...       ...
95   12  Female  104.0    Mild  Bangalore        No
96   51  Female  101.0  Strong    Kolkata       Yes
97   20  Female  101.0    Mild  Bangalore        No
98    5  Female   98.0  Strong     Mumbai        No
99   10  Female   98.0  Strong    Kolkata       Yes

[100 rows x 6 columns]

In [ ]:
import pandas as pd

transformed_df = pd.DataFrame(hell)
transformed_df.head()

            0    1    2    3    4    5     6
0  102.000000  0.0  1.0  0.0  0.0  0.0  64.0
1  101.138889  1.0  0.0  0.0  0.0  1.0  34.0
2  101.138889  0.0  1.0  0.0  1.0  0.0  82.0
3  101.000000  1.0  0.0  0.0  1.0  0.0  51.0
4  104.000000  0.0  1.0  0.0  0.0  0.0  25.0

In [21]:
transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    # Add sparse_output=False here
    ('tnf3', OneHotEncoder(drop='first', sparse_output=False), ['gender', 'city'])
], remainder='passthrough')


transformer.set_output(transform="pandas")
hell = transformer.fit_transform(X_train)


transformer.set_output(transform="pandas")


hell1= transformer.fit_transform(X_train)
hell2= transformer.fit_transform(X_test)
hell3= transformer.fit_transform(y_train)
hell3= transformer.fit_transform(y_test)
hell4=df[:]

IndexError: tuple index out of range

In [22]:

transformer = ColumnTransformer(transformers=[
    ('tnf1', SimpleImputer(), ['fever']),
    ('tnf2', OrdinalEncoder(categories=[['Mild', 'Strong']]), ['cough']),
    ('tnf3', OneHotEncoder(drop='first',sparse_output=False), ['gender', 'city'])
], remainder='passthrough')

transformer.set_output(transform="pandas")


hell = transformer.fit_transform(X_train)

hell

,tnf1__fever,tnf2__cough,tnf3__gender_Male,tnf3__city_Delhi,tnf3__city_Kolkata,tnf3__city_Mumbai,remainder__age
13,102.000000,0.0,1.0,0.0,0.0,0.0,64
29,101.138889,1.0,0.0,0.0,0.0,1.0,34
41,101.138889,0.0,1.0,0.0,1.0,0.0,82
96,101.000000,1.0,0.0,0.0,1.0,0.0,51
86,104.000000,0.0,1.0,0.0,0.0,0.0,25
...,...,...,...,...,...,...,...
55,101.000000,0.0,0.0,0.0,0.0,1.0,81
58,98.000000,1.0,1.0,0.0,0.0,1.0,23
50,101.000000,0.0,1.0,1.0,0.0,0.0,19
82,98.000000,0.0,1.0,0.0,1.0,0.0,24
65,102.000000,0.0,0.0,0.0,0.0,0.0,69