In [1]:
print('hell ')

hell

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [7]:
df = pd.read_csv('placement.csv')

In [11]:
df.shape

(200, 2)

In [14]:
print("Mean value of cgpa",df['cgpa'].mean())
print("Std value of cgpa",df['cgpa'].std())
print("Min value of cgpa",df['cgpa'].min())
print("Max value of cgpa",df['cgpa'].max())

Mean value of cgpa 6.990500000000001
Std value of cgpa 1.0694086798895526
Min value of cgpa 4.26
Max value of cgpa 9.58

In [15]:
# Finding the boundary values
print("Highest allowed",df['cgpa'].mean() + 3*df['cgpa'].std())
print("Lowest allowed",df['cgpa'].mean() - 3*df['cgpa'].std())

Highest allowed 10.198726039668658
Lowest allowed 3.7822739603313433

In [16]:
# Finding the outliers
df[(df['cgpa'] > 8.80) | (df['cgpa'] < 5.11)]

     cgpa  package
12   8.94     3.65
40   9.38     4.02
44   5.09     1.86
49   8.87     4.62
50   9.58     4.43
51   9.26     3.79
63   9.16     4.25
77   8.99     4.60
84   4.26     1.53
85   4.79     1.48
88   4.73     1.48
116  9.04     3.33
123  5.10     2.30
143  4.85     1.54
163  8.93     3.91
164  9.06     3.82
169  9.31     4.37
193  4.57     1.94

In [17]:
# Trimming

new_df = df[(df['cgpa'] < 8.80) & (df['cgpa'] > 5.11)]
new_df

     cgpa  package
0    6.89     3.26
1    5.12     1.98
2    7.82     3.25
3    7.42     3.67
4    6.94     3.57
..    ...      ...
195  6.93     2.46
196  5.89     2.57
197  7.21     3.24
198  7.63     3.96
199  6.22     2.33

[181 rows x 2 columns]

In [18]:
df['cgpa_zscore'] = (df['cgpa'] - df['cgpa'].mean())/df['cgpa'].std()

In [19]:
df.head()

   cgpa  package  cgpa_zscore
0  6.89     3.26    -0.093977
1  5.12     1.98    -1.749097
2  7.82     3.25     0.775662
3  7.42     3.67     0.401624
4  6.94     3.57    -0.047222

In [20]:
df[df['cgpa_zscore'] > 3]

Empty DataFrame
Columns: [cgpa, package, cgpa_zscore]
Index: []

In [21]:
df[df['cgpa_zscore'] < -3]

Empty DataFrame
Columns: [cgpa, package, cgpa_zscore]
Index: []

In [ ]:
upper_limit = df['cgpa'].mean() + 3*df['cgpa'].std()
lower_limit = df['cgpa'].mean() - 3*df['cgpa'].std()

In [ ]:
lower_limit

In [ ]:
df['cgpa'] = np.where(
    df['cgpa']>upper_limit,
    upper_limit,
    np.where(
        df['cgpa']<lower_limit,
        lower_limit,
        df['cgpa']
    )
)